"use client";

import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import {ArrowRight,ArrowUpRight,Bot,Boxes,Code2,FileText,History,Home,Image as ImageIcon,Moon,PanelLeftClose,Search,Settings as SettingsIcon,Star,Sun} from "lucide-react";
import {motion} from "framer-motion";
import { categories, categoryLabels, tools, type Category, type Tool } from "@/lib/tools";
import { categoryName, translate, useAppLanguage } from "@/lib/language";

const categoryIcon: Record<string,React.ComponentType<{size?:number;strokeWidth?:number}>> = {developer:Code2,media:ImageIcon,pdf:FileText,ai:Bot};
const readList=(key:string):string[]=>{try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}};

export function Workspace({children}:{children:React.ReactNode}) {
  const pathname=usePathname(), router=useRouter();
  const language=useAppLanguage(),t=(text:string)=>translate(text,language);
  const [dark,setDark]=useState(false),[collapsed,setCollapsed]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[recent,setRecent]=useState<string[]>([]),[query,setQuery]=useState(""),[palette,setPalette]=useState(false);
  useEffect(()=>{const saved=localStorage.getItem("imphnen-theme");setDark(saved==="dark");setFavorites(readList("imphnen-favorites"));setRecent(readList("imphnen-recent"));const sync=()=>{setFavorites(readList("imphnen-favorites"));setRecent(readList("imphnen-recent"))};const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(v=>!v)}if(e.key==="Escape")setPalette(false)};window.addEventListener("keydown",key);window.addEventListener("imphnen-local-update",sync);return()=>{window.removeEventListener("keydown",key);window.removeEventListener("imphnen-local-update",sync)}},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("imphnen-theme",dark?"dark":"light")},[dark]);
  const filtered=useMemo(()=>tools.filter(item=>`${item.name} ${item.description} ${categoryLabels[item.category]} ${translate(item.name,language)} ${translate(item.description,language)}`.toLowerCase().includes(query.toLowerCase())).slice(0,8),[query,language]);
  const toggleFavorite=(slug:string)=>{const next=favorites.includes(slug)?favorites.filter(x=>x!==slug):[...favorites,slug];setFavorites(next);localStorage.setItem("imphnen-favorites",JSON.stringify(next));window.dispatchEvent(new Event("imphnen-local-update"))};
  const go=(tool:Tool)=>{const next=[tool.slug,...recent.filter(x=>x!==tool.slug)].slice(0,8);setRecent(next);localStorage.setItem("imphnen-recent",JSON.stringify(next));window.dispatchEvent(new Event("imphnen-local-update"));setPalette(false);setQuery("");router.push(`/tools/${tool.slug}`)};
  const nav=(href:string)=>pathname===href;
  return <div className={`shell ${collapsed?"is-collapsed":""}`}>
    <aside className="sidebar">
      <Link href="/" className="brand"><Image className="brand-image" src="/imphnen-sidebar-logo.png" alt="IMPHNEN" width={950} height={530} unoptimized/><span className="brand-text brand-subtitle"><small>ONLINE TOOLS</small></span></Link>
      <div className="workspace-pill"><span className="workspace-dot"/> {t("Personal workspace")} <span className="chevron">⌄</span></div>
      <nav aria-label="Main navigation">
        <div className="nav-label">{t("WORKSPACE")}</div>
        <Link title={t("Home")} aria-label={t("Home")} className={`nav-item ${nav("/")?"active":""}`} href="/"><span><Home size={15}/></span><span className="nav-item-label">{t("Home")}</span></Link>
        <Link title={t("All tools")} aria-label={t("All tools")} className={`nav-item ${pathname==="/all-tools"?"active":""}`} href="/all-tools"><span><Boxes size={15}/></span><span className="nav-item-label">{t("All tools")}</span><kbd>⌘ 1</kbd></Link>
        <div className="nav-label nav-label-spaced">{t("CATEGORIES")}</div>
        {categories.filter(c=>c.id!=="all").map(c=>{const Icon=categoryIcon[c.id],label=categoryName(c.id,language);return <Link key={c.id} title={label} aria-label={label} className={`nav-item ${pathname===`/category/${c.id}`?"active":""}`} href={`/category/${c.id}`}><span><Icon size={15}/></span><span className="nav-item-label">{label}</span><i className="nav-count">{c.count}</i></Link>})}
        <div className="nav-label nav-label-spaced">{t("YOUR LIBRARY")}</div>
        <Link title={t("Favorites")} aria-label={t("Favorites")} className={`nav-item ${nav("/favorites")?"active":""}`} href="/favorites"><span><Star size={15}/></span><span className="nav-item-label">{t("Favorites")}</span> {favorites.length>0&&<i className="nav-count">{favorites.length}</i>}</Link>
        <Link title={t("Recent")} aria-label={t("Recent")} className={`nav-item ${nav("/recent")?"active":""}`} href="/recent"><span><History size={15}/></span><span className="nav-item-label">{t("Recent")}</span></Link>
      </nav>
  <div className="sidebar-bottom">
        <Link title={t("Settings")} aria-label={t("Settings")} className="nav-item" href="/settings"><span><SettingsIcon size={15}/></span><span className="nav-item-label">{t("Settings")}</span></Link><button title={dark?t("Light mode"):t("Dark mode")} aria-label={dark?t("Light mode"):t("Dark mode")} className="nav-item theme-button" onClick={()=>setDark(!dark)}><span>{dark?<Sun size={15}/>:<Moon size={15}/>}</span><span className="nav-item-label">{dark?t("Light mode"):t("Dark mode")}</span><i className="theme-toggle"><i/></i></button>
        <button className="collapse-button" onClick={()=>setCollapsed(!collapsed)} aria-label={t(collapsed?"Expand sidebar":"Collapse sidebar")} title={t(collapsed?"Expand sidebar":"Collapse sidebar")}><span><PanelLeftClose size={14}/></span><span className="nav-item-label">{t(collapsed?"Expand sidebar":"Collapse sidebar")}</span></button>
        <div className="profile"><div className="avatar">I</div><div><b>{t("Guest workspace")}</b><small>{t("Free plan")}</small></div><span className="profile-more">···</span></div>
      </div>
    </aside>
    <main className="main-area"><header className="topbar"><div className="breadcrumbs"><span>{t("Workspace")}</span><b>/</b><strong>{t(pathname==="/"?"Home":pathname.split("/").filter(Boolean).at(-1)?.replaceAll("-"," ")||"Home")}</strong></div><div className="top-actions"><button className="top-search" onClick={()=>setPalette(true)}><span><Search size={15}/></span> {t("Search anything...")} <kbd>⌘ K</kbd></button></div></header>
      <div className="page-content">{children}</div>
      <footer className="site-footer"><div className="footer-main"><Link href="/" className="footer-brand"><span className="brand-mark">i</span><span><b>IMPHNEN</b><small>ONLINE TOOLS</small></span></Link><p>{t("All your tools. One place.")}</p><div className="footer-links"><section><b>{t("Explore")}</b><Link href="/all-tools">{t("All tools")}</Link><Link href="/category/developer">{t("Developer")}</Link><Link href="/category/media">{t("Media")}</Link></section><section><b>{t("More tools")}</b><Link href="/category/pdf">PDF</Link><Link href="/category/ai">AI</Link><Link href="/favorites">{t("Favorites")}</Link></section><section><b>{t("About")}</b><Link href="/about">{t("Our mission")}</Link><Link href="/privacy">{t("Privacy")}</Link><Link href="/terms">{t("Terms")}</Link></section></div></div><div className="footer-bottom"><span>© 2026 IMPHNEN ONLINE TOOLS</span><span className="status-live"><i/> {t("Ready when you are")}</span></div></footer>
    </main>
    {palette&&<div className="palette-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setPalette(false)}}><div className="command-palette" role="dialog" aria-modal="true" aria-label={t("Search tools")}><div className="palette-input"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("Search tools, categories...")}/><kbd>ESC</kbd></div><div className="palette-hint">{query?t("SEARCH RESULTS"):t("QUICK ACCESS")}</div>{(query?filtered:tools.filter(t=>t.popular).slice(0,6)).map(t=><button className="palette-result" key={t.slug} onClick={()=>go(t)}><span className={`mini-icon ${t.category}`}>{t.icon}</span><span><b>{translate(t.name,language)}</b><small>{translate(categoryLabels[t.category],language)}</small></span><span className="result-enter">↵</span></button>)}{query&&filtered.length===0&&<div className="empty-search">{language==="Indonesian"?`Alat tidak ditemukan untuk “${query}”`:`No tools found for “${query}”`}</div>}<div className="palette-footer"><span>↑↓ {t("Navigate")}</span><span>↵ {t("Open tool")}</span><span>ESC {t("Close")}</span></div></div></div>}
  </div>
}

export function ToolCard({tool,favorite=false,onFavorite}:{tool:Tool;favorite?:boolean;onFavorite?:(slug:string)=>void}) { const Icon=categoryIcon[tool.category],language=useAppLanguage(),t=(text:string)=>translate(text,language);return <motion.article layout whileHover={{y:-2}} transition={{duration:.16}} className="tool-card"><Link href={`/tools/${tool.slug}`} className="tool-link"><div className={`tool-icon ${tool.category}`}>{tool.icon}</div><span className="card-open"><ArrowUpRight size={13}/></span><h3>{t(tool.name)}</h3><p>{t(tool.description)}</p><div className="tool-card-bottom"><span className={`category-tag ${tool.category}`}><i><Icon size={10}/></i>{translate(categoryLabels[tool.category],language)}</span><span className="open-label">{t("Open tool")} <b><ArrowRight size={11}/></b></span></div></Link>{onFavorite&&<button className={`favorite-btn ${favorite?"is-favorite":""}`} aria-label={favorite?t("Remove from favorites"):t("Add to favorites")} onClick={()=>onFavorite(tool.slug)}>{favorite?"★":"☆"}</button>}</motion.article> }

export function ToolGrid({items,favorites=[],onFavorite}:{items:Tool[];favorites?:string[];onFavorite?:(slug:string)=>void}){const language=useAppLanguage(),t=(text:string)=>translate(text,language);return items.length?<div className="tool-grid">{items.map(t=><ToolCard key={t.slug} tool={t} favorite={favorites.includes(t.slug)} onFavorite={onFavorite}/>)}</div>:<div className="empty-state"><span>⌕</span><h3>{t("Nothing here yet")}</h3><p>{t("Tools you save or use will show up here.")}</p><Link href="/all-tools" className="button-secondary">{t("Browse all tools")} <b>→</b></Link></div>}

export function HomePage(){
 const language=useAppLanguage(),t=(text:string)=>translate(text,language);
 const [filter,setFilter]=useState<Category|"all">("all"),[query,setQuery]=useState(""),[favorites,setFavorites]=useState<string[]>([]),[recent,setRecent]=useState<string[]>([]),[greeting,setGreeting]=useState("Good morning"),[dateLabel,setDateLabel]=useState("");
 useEffect(()=>{setFavorites(readList("imphnen-favorites"));setRecent(readList("imphnen-recent"));const now=new Date();setGreeting(now.getHours()<12?"Good morning":now.getHours()<18?"Good afternoon":"Good evening");setDateLabel(new Intl.DateTimeFormat(language==="Indonesian"?"id-ID":"en-US",{weekday:"long",month:"long",day:"numeric"}).format(now).toUpperCase())},[language]);
 const items=tools.filter(item=>(filter==="all"||item.category===filter)&&`${item.name} ${item.description} ${categoryLabels[item.category]} ${translate(item.name,language)} ${translate(item.description,language)}`.toLowerCase().includes(query.toLowerCase()));
 const toggle=(slug:string)=>{const next=favorites.includes(slug)?favorites.filter(x=>x!==slug):[...favorites,slug];setFavorites(next);localStorage.setItem("imphnen-favorites",JSON.stringify(next));window.dispatchEvent(new Event("imphnen-local-update"))};
 const recentItems=recent.map(slug=>tools.find(t=>t.slug===slug)).filter((x):x is Tool=>!!x);
 return <>
  <section className="welcome-row"><div><div className="eyebrow"><span className="eyebrow-line"/> {t("YOUR CREATIVE WORKSPACE")}</div><h1>{t(greeting)}<span className="wave">✳</span></h1><p>{t("What can we help you get done today?")}</p></div><div className="welcome-date"><span className="date-icon">◷</span><div><small>{dateLabel}</small><b>{t("One less tab to worry about.")}</b></div></div></section>
  <section className="hero-panel"><div className="hero-copy"><div className="hero-kicker"><i/> {t("YOUR ALL-IN-ONE TOOLKIT")}</div><h2>{t("All your tools.")}<br/><span>{t("One place.")}</span></h2><p>{t("Powerful online tools for developers, creators, students, and everyone else.")}</p><button className="hero-cta" onClick={()=>document.getElementById("tool-explorer")?.scrollIntoView({behavior:"smooth"})}>{t("Explore all tools")} <b>↗</b></button><div className="hero-trust"><span><i>✓</i> {t("No sign-up required")}</span><span><i>◈</i> {t("Privacy-first")}</span><span><i>⚡</i> {t("Fast by design")}</span></div></div><Image className="hero-brand-image" src="/imphnen-brand-art-transparent.png" alt="IMPHNEN: Ingin Menjadi Programmer Handal, Namun Enggan Ngoding" width={1338} height={906} priority unoptimized/><div className="hero-decoration">I<span>✳</span></div></section>
  <section className="stats-row"><div className="stat-item"><span className="stat-icon coral">⌘</span><div><b>45+</b><small>{t("Powerful tools")}</small></div></div><div className="stat-item"><span className="stat-icon lavender">ϟ</span><div><b>100%</b><small>{t("Free to use")}</small></div></div><div className="stat-item"><span className="stat-icon green">◈</span><div><b>{t("Private")}</b><small>{t("By default")}</small></div></div><div className="stat-item"><span className="stat-icon yellow">↗</span><div><b>{t("Instant")}</b><small>{t("No waiting around")}</small></div></div></section>
  {recentItems.length>0&&<section className="content-section recent-section"><div className="section-heading"><div><span className="section-kicker">{t("PICK UP WHERE YOU LEFT OFF")}</span><h2>{t("Recently used")} <span>↗</span></h2></div><Link href="/recent" className="text-link">{t("See history")} <b>→</b></Link></div><div className="recent-strip">{recentItems.slice(0,4).map(t=><Link key={t.slug} className="recent-chip" href={`/tools/${t.slug}`}><span className={`mini-icon ${t.category}`}>{t.icon}</span><span><b>{translate(t.name,language)}</b><small>{translate(categoryLabels[t.category],language)}</small></span><span className="chip-arrow">↗</span></Link>)}</div></section>}
  <section id="tool-explorer" className="content-section explorer-section"><div className="section-heading"><div><span className="section-kicker">{t("THE WHOLE TOOLKIT")}</span><h2>{t("Find your next tool")} <span>✳</span></h2><p>{t("Everything you need, right at your fingertips.")}</p></div><label className="inline-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("Search all tools...")}/><kbd>⌘ K</kbd></label></div><div className="filter-tabs" role="tablist">{categories.map(c=><button key={c.id} role="tab" aria-selected={filter===c.id} className={filter===c.id?"selected":""} onClick={()=>setFilter(c.id)}><span>{c.icon}</span>{categoryName(c.id,language)}<i>{c.count}</i></button>)}</div>
   {filter==="all"&&!query?<><section className="tool-category"><div className="category-title"><span className="category-heading-icon popular-icon">✦</span><div><h3>{t("Popular right now")}</h3><p>{t("The tools everyone keeps coming back to.")}</p></div><Link href="/all-tools" className="text-link">{t("View all")} <b>→</b></Link></div><ToolGrid items={tools.filter(t=>t.popular).slice(0,4)} favorites={favorites} onFavorite={toggle}/></section>{categories.filter(c=>c.id!=="all").map(c=><section className="tool-category" key={c.id}><div className="category-title"><span className={`category-heading-icon ${c.id}`}>{c.icon}</span><div><h3>{categoryName(c.id,language)}</h3><p>{t(c.id==="developer"?"Thoughtful tools for your everyday workflow.":c.id==="media"?"Make your images and media work harder.":c.id==="pdf"?"A simpler way to get documents done.":"A little intelligence goes a long way.")}</p></div><Link href={`/category/${c.id}`} className="text-link">{t("See all")} {c.count} <b>→</b></Link></div><ToolGrid items={tools.filter(t=>t.category===c.id).slice(0,3)} favorites={favorites} onFavorite={toggle}/></section>)}</>:<section className="tool-category search-grid"><div className="results-label">{items.length} {t(items.length===1?"tool found":"tools found")}</div><ToolGrid items={items} favorites={favorites} onFavorite={toggle}/></section>}
  </section>
  <section className="privacy-banner"><div className="privacy-emblem">◈</div><div><span>{t("YOUR FILES STAY YOURS")}</span><h3>{t("Private by design. Every time.")}</h3><p>{t("Tools marked with a lock process your files locally in your browser. Your work stays yours.")}</p></div><Link href="/about" className="button-secondary">{t("How we protect you")} <b>→</b></Link><div className="privacy-watermark">◈</div></section>
  <section className="bottom-cta"><div className="cta-spark">✳</div><div><h3>{t("A tool for that?")} <span>{t("There probably is.")}</span></h3><p>{t("Explore the whole collection and get back to what matters.")}</p></div><button onClick={()=>{setFilter("all");document.getElementById("tool-explorer")?.scrollIntoView({behavior:"smooth"})}} className="button-primary">{t("Explore the toolkit")} <b>↗</b></button><div className="cta-pattern">✳</div></section>
  </>;
}
