"use client";

import { useEffect, useState } from "react";

export type AppLanguage = "English" | "Indonesian";

const id: Record<string, string> = Object.fromEntries([
    ["Personal workspace", "Ruang kerja pribadi"],
    ["WORKSPACE", "RUANG KERJA"],
    ["CATEGORIES", "KATEGORI"],
    ["YOUR LIBRARY", "KOLEKSI ANDA"],
    ["Light mode", "Mode terang"],
    ["Dark mode", "Mode gelap"],
    ["System", "Sistem"],
    ["Workspace", "Ruang kerja"],
    ["Explore", "Jelajahi"],
    ["More tools", "Alat lainnya"],
    ["Our mission", "Misi kami"],
    ["Ready when you are", "Siap kapan saja"],
    ["Search tools", "Cari alat"],
    ["SEARCH RESULTS", "HASIL PENCARIAN"],
    ["QUICK ACCESS", "AKSES CEPAT"],
    ["Navigate", "Navigasi"],
    ["Close", "Tutup"],
    ["Remove from favorites", "Hapus dari favorit"],
    ["Add to favorites", "Tambahkan ke favorit"],
    ["or", "atau"],
    ["Collapse sidebar", "Ciutkan sidebar"],
    ["Guest workspace", "Ruang kerja tamu"],
    ["Free plan", "Paket gratis"],
    ["Instant", "Instan"],
    ["No tools found", "Alat tidak ditemukan"],
    ["Browse all tools", "Jelajahi semua alat"],
    ["Home", "Beranda"],
    ["All tools", "Semua alat"],
    ["Developer", "Developer"],
    ["Media", "Media"],
    ["PDF", "PDF"],
    ["AI tools", "Alat AI"],
    ["Developer tools", "Alat developer"],
    ["Media tools", "Alat media"],
    ["PDF tools", "Alat PDF"],
    ["AI tools", "Alat AI"],
    ["Favorites", "Favorit"],
    ["Your favorites", "Favorit Anda"],
    ["Recent", "Terbaru"],
    ["Recently used", "Baru digunakan"],
    ["Settings", "Pengaturan"],
    ["About", "Tentang"],
    ["Privacy", "Privasi"],
    ["Terms", "Ketentuan"],
    ["Search anything...", "Cari apa saja..."],
    ["Search tools, categories...", "Cari alat atau kategori..."],
    ["Search all tools...", "Cari semua alat..."],
    ["Search", "Cari"],
    ["Open tool", "Buka alat"],
    ["Open", "Buka"],
    ["View all", "Lihat semua"],
    ["See all", "Lihat semua"],
    ["Browse tools", "Jelajahi alat"],
    ["Browse category", "Jelajahi kategori"],
    ["Explore the toolkit", "Jelajahi semua alat"],
    ["Explore all tools", "Jelajahi semua alat"],
    ["YOUR CREATIVE WORKSPACE", "RUANG KERJA KREATIF ANDA"],
    ["Good morning", "Selamat pagi"],
    ["Good afternoon", "Selamat siang"],
    ["Good evening", "Selamat malam"],
    ["What can we help you get done today?", "Apa yang ingin Anda selesaikan hari ini?"],
    ["One less tab to worry about.", "Lebih sedikit tab, lebih fokus."],
    ["YOUR ALL-IN-ONE TOOLKIT", "SEMUA ALAT DALAM SATU TEMPAT"],
    ["All your tools.", "Semua alat Anda."],
    ["One place.", "Satu tempat."],
    ["Powerful online tools for developers, creators, students, and everyone else.", "Alat online praktis untuk developer, kreator, pelajar, dan siapa saja."],
    ["No sign-up required", "Tanpa perlu mendaftar"],
    ["Privacy-first", "Utamakan privasi"],
    ["Fast by design", "Dirancang cepat"],
    ["Powerful tools", "Alat praktis"],
    ["Free to use", "Gratis digunakan"],
    ["Private", "Privat"],
    ["By default", "Sejak awal"],
    ["Instant", "Instan"],
    ["No waiting around", "Tanpa menunggu lama"],
    ["PICK UP WHERE YOU LEFT OFF", "LANJUTKAN AKTIVITAS ANDA"],
    ["Recently used", "Baru digunakan"],
    ["See history", "Lihat riwayat"],
    ["THE WHOLE TOOLKIT", "SEMUA ALAT"],
    ["Find your next tool", "Temukan alat yang Anda butuhkan"],
    ["Everything you need, right at your fingertips.", "Semua yang Anda butuhkan, siap digunakan."],
    ["All tools", "Semua alat"],
    ["Popular right now", "Populer saat ini"],
    ["The tools everyone keeps coming back to.", "Alat yang sering digunakan."],
    ["Thoughtful tools for your everyday workflow.", "Alat praktis untuk pekerjaan sehari-hari."],
    ["Make your images and media work harder.", "Olah gambar dan media dengan mudah."],
    ["A simpler way to get documents done.", "Selesaikan urusan dokumen dengan lebih mudah."],
    ["A little intelligence goes a long way.", "AI yang membantu pekerjaan Anda."],
    ["Find your next tool", "Temukan alat yang Anda butuhkan"],
    ["tools found", "alat ditemukan"],
    ["tool found", "alat ditemukan"],
    ["YOUR FILES STAY YOURS", "FILE ANDA TETAP MILIK ANDA"],
    ["Private by design. Every time.", "Privasi selalu menjadi prioritas."],
    ["Tools marked with a lock process your files locally in your browser. Your work stays yours.", "Alat bertanda gembok memproses file langsung di browser. File Anda tetap milik Anda."],
    ["How we protect you", "Cara kami melindungi Anda"],
    ["A tool for that?", "Butuh alat untuk itu?"],
    ["There probably is.", "Mungkin sudah tersedia."],
    ["Explore the whole collection and get back to what matters.", "Jelajahi semua alat dan lanjutkan pekerjaan Anda."],
    ["YOUR PERSONAL COLLECTION", "KOLEKSI PRIBADI ANDA"],
    ["YOUR WORKSPACE HISTORY", "RIWAYAT RUANG KERJA"],
    ["THE IMPHNEN TOOLKIT", "KOLEKSI ALAT IMPHNEN"],
    ["Your go-to tools, all in one place.", "Alat pilihan Anda, terkumpul di satu tempat."],
    ["Jump back into something you were working on.", "Lanjutkan pekerjaan yang terakhir Anda buka."],
    ["A little something for every task. Pick a tool and get going.", "Temukan alat untuk berbagai kebutuhan dan mulai bekerja."],
    ["TOOLS AVAILABLE", "ALAT TERSEDIA"],
    ["Privacy-first processing", "Pemrosesan yang mengutamakan privasi"],
    ["SHOWING", "MENAMPILKAN"],
    ["TOOL", "ALAT"],
    ["TOOLS", "ALAT"],
    ["Nothing here yet", "Belum ada apa pun di sini"],
    ["Tools you save or use will show up here.", "Alat yang Anda simpan atau gunakan akan muncul di sini."],
    ["MAKE YOURSELF AT HOME", "SESUAIKAN DENGAN KEBUTUHAN ANDA"],
    ["Make your workspace feel a little more like yours.", "Atur ruang kerja agar terasa lebih personal."],
    ["Appearance", "Tampilan"],
    ["Choose how IMPHNEN ONLINE TOOLS looks on this device.", "Pilih tampilan IMPHNEN ONLINE TOOLS di perangkat ini."],
    ["Language", "Bahasa"],
    ["Choose your preferred language.", "Pilih bahasa yang ingin digunakan."],
    ["Indonesian", "Bahasa Indonesia"],
    ["Privacy & data", "Privasi & data"],
    ["Clear the tools stored in this browser.", "Hapus data alat yang tersimpan di browser ini."],
    ["Clear recent tools", "Hapus riwayat alat"],
    ["Clear favorites", "Hapus daftar favorit"],
    ["Keyboard shortcuts", "Pintasan keyboard"],
    ["Open search from anywhere in your workspace.", "Buka pencarian dari mana saja di ruang kerja."],
    ["Preferences updated", "Preferensi diperbarui"],
    ["Personal workspace", "Ruang kerja pribadi"],
    ["WORKSPACE", "RUANG KERJA"],
    ["CATEGORIES", "KATEGORI"],
    ["YOUR LIBRARY", "KOLEKSI ANDA"],
    ["Light mode", "Mode terang"],
    ["Dark mode", "Mode gelap"],
    ["system", "Sistem"],
    ["Workspace", "Ruang kerja"],
    ["Explore", "Jelajahi"],
    ["More tools", "Alat lainnya"],
    ["Our mission", "Misi kami"],
    ["All your tools. One place.", "Semua alat Anda. Satu tempat."],
    ["Ready when you are", "Siap kapan saja"],
    ["Search tools", "Cari alat"],
    ["SEARCH RESULTS", "HASIL PENCARIAN"],
    ["QUICK ACCESS", "AKSES CEPAT"],
    ["Navigate", "Navigasi"],
    ["Close", "Tutup"],
    ["Remove from favorites", "Hapus dari favorit"],
    ["Add to favorites", "Tambahkan ke favorit"],
    ["or", "atau"],
    ["All your tools, one place", "Semua alat Anda, satu tempat"],
    ["Input", "Masukan"],
    ["Text input", "Masukan teks"],
    ["Enter your content below to get started.", "Masukkan konten di bawah untuk memulai."],
    ["Text is sent to your configured AI provider.", "Teks dikirim ke penyedia AI yang dikonfigurasi."],
    ["Run tool", "Jalankan alat"],
    ["Generate password", "Buat kata sandi"],
    ["Summarize", "Ringkas"],
    ["Rewrite text", "Tulis ulang teks"],
    ["Translate", "Terjemahkan"],
    ["Analyze text", "Analisis teks"],
    ["Processing…", "Memproses…"],
    ["Clear", "Hapus"],
    ["Result", "Hasil"],
    ["Copy", "Salin"],
    ["Download", "Unduh"],
    ["Copied to clipboard.", "Disalin ke papan klip."],
    ["Pick a color", "Pilih warna"],
    ["Password length", "Panjang kata sandi"],
    ["Pattern", "Pola"],
    ["Flags", "Flag"],
    ["Modified text...", "Teks yang diubah..."],
    ["Compare the original with the modified text.", "Bandingkan teks asli dengan teks yang diubah."],
    ["Type or paste your input here...", "Ketik atau tempel masukan Anda di sini..."],
    ["No matches found.", "Tidak ada kecocokan."],
    ["No differences found.", "Tidak ada perbedaan."],
    ["Status code not found. Enter a standard HTTP code, such as 404.", "Kode status tidak ditemukan. Masukkan kode HTTP standar, misalnya 404."],
    ["Something went wrong. Check your input and try again.", "Terjadi kesalahan. Periksa masukan lalu coba lagi."],
    ["Invalid input. Check the value and try again.", "Masukan tidak valid. Periksa nilainya lalu coba lagi."],
    ["Choose a PNG, JPG, WebP, or AVIF image.", "Pilih gambar PNG, JPG, WebP, atau AVIF."],
    ["File must be smaller than 25 MB.", "Ukuran file harus di bawah 25 MB."],
    ["Simple by design", "Sederhana dan praktis"],
    ["No setup. Open the tool and get straight to work.", "Tanpa pengaturan. Buka alat dan langsung mulai."],
    ["Your privacy comes first", "Privasi Anda yang utama"],
    ["This tool runs locally in your browser.", "Alat ini berjalan langsung di browser Anda."],
    ["Built for everyone", "Dibuat untuk semua orang"],
    ["Clear controls and useful results, without the clutter.", "Kontrol yang jelas dan hasil berguna tanpa tampilan rumit."],
    ["KEEP EXPLORING", "JELAJAHI LEBIH LANJUT"],
    ["More", "Lainnya"],
    ["Browse category →", "Lihat kategori →"],
    ["JSON Formatter", "Pemformat JSON"],
    ["Format, validate and minify JSON with a clean tree view.", "Format, validasi, dan ringkas JSON dengan tampilan struktur yang rapi."],
    ["JWT Decoder", "Dekoder JWT"],
    ["Inspect token headers and payloads. Signature is never verified.", "Periksa header dan payload token. Tanda tangan tidak diverifikasi."],
    ["UUID Generator", "Generator UUID"],
    ["Generate secure UUID v4 identifiers in seconds.", "Buat UUID v4 yang aman dalam hitungan detik."],
    ["Base64 Converter", "Konverter Base64"],
    ["Encode text or decode Base64 right in your browser.", "Enkode teks atau dekode Base64 langsung di browser."],
    ["URL Encoder / Decoder", "Enkoder / Dekoder URL"],
    ["Encode and decode URL components safely.", "Enkode dan dekode bagian URL dengan aman."],
    ["Hash Generator", "Generator Hash"],
    ["Create MD5, SHA-1, SHA-256 and SHA-512 digests.", "Buat hash MD5, SHA-1, SHA-256, dan SHA-512."],
    ["Regex Tester", "Penguji Regex"],
    ["Test patterns, flags and capture groups interactively.", "Uji pola, flag, dan grup tangkapan secara interaktif."],
    ["Diff Checker", "Pemeriksa Perbedaan"],
    ["Compare two texts and spot additions and removals.", "Bandingkan dua teks dan temukan bagian yang ditambah atau dihapus."],
    ["Timestamp Converter", "Konverter Timestamp"],
    ["Convert Unix timestamps and dates instantly.", "Konversi timestamp Unix dan tanggal dengan cepat."],
    ["Cron Generator", "Generator Cron"],
    ["Build a cron expression from a readable schedule.", "Buat ekspresi cron dari jadwal yang mudah dibaca."],
    ["SQL Formatter", "Pemformat SQL"],
    ["Make SQL queries easier to read and review.", "Buat kueri SQL lebih mudah dibaca dan ditinjau."],
    ["HTML Minifier", "Minifier HTML"],
    ["Remove unnecessary whitespace from HTML.", "Hapus spasi yang tidak diperlukan dari HTML."],
    ["CSS Minifier", "Minifier CSS"],
    ["Compress CSS source for smaller files.", "Ringkas kode CSS agar ukuran file lebih kecil."],
    ["JavaScript Minifier", "Minifier JavaScript"],
    ["Compact compatible JavaScript source code.", "Ringkas kode JavaScript yang kompatibel."],
    ["Markdown Preview", "Pratinjau Markdown"],
    ["Write Markdown and preview the rendered result.", "Tulis Markdown dan lihat hasil tampilannya."],
    ["URL Parser", "Pengurai URL"],
    ["Inspect URL parts and query parameters.", "Periksa bagian URL dan parameter kueri."],
    ["HTTP Status Checker", "Pemeriksa Status HTTP"],
    ["Look up standard HTTP response status codes.", "Cari kode status respons HTTP standar."],
    ["Image Compressor", "Kompresor Gambar"],
    ["Reduce image size and compare the result before download.", "Kecilkan ukuran gambar dan bandingkan hasilnya sebelum mengunduh."],
    ["Image Resizer", "Pengubah Ukuran Gambar"],
    ["Resize images with an optional locked aspect ratio.", "Ubah ukuran gambar dengan rasio aspek yang dapat dikunci."],
    ["Image Converter", "Konverter Gambar"],
    ["Convert images between PNG, JPEG and WebP.", "Konversi gambar antara PNG, JPEG, dan WebP."],
    ["Color Picker", "Pemilih Warna"],
    ["Explore a color and copy HEX, RGB or HSL values.", "Pilih warna dan salin nilai HEX, RGB, atau HSL."],
    ["QR Generator", "Generator QR"],
    ["Create a QR code for links, text, WiFi and contacts.", "Buat kode QR untuk tautan, teks, WiFi, dan kontak."],
    ["Background Remover", "Penghapus Latar Belakang"],
    ["Remove image backgrounds with an AI provider.", "Hapus latar belakang gambar dengan penyedia AI."],
    ["GIF Maker", "Pembuat GIF"],
    ["Turn image frames into an animated GIF.", "Ubah rangkaian gambar menjadi GIF animasi."],
    ["Video Compressor", "Kompresor Video"],
    ["Compress video with control over output quality.", "Kompres video dengan pengaturan kualitas hasil."],
    ["Audio Converter", "Konverter Audio"],
    ["Convert common audio formats.", "Konversi format audio umum."],
    ["Video to GIF", "Konverter Video ke GIF"],
    ["Create a GIF from a video clip.", "Buat GIF dari klip video."],
    ["Screenshot to Image", "Tangkapan Layar ke Gambar"],
    ["Capture a selected screen and save it as an image.", "Ambil tangkapan layar dan simpan sebagai gambar."],
    ["Merge PDF", "Gabungkan PDF"],
    ["Combine PDF documents into one file.", "Gabungkan beberapa dokumen PDF menjadi satu file."],
    ["Split PDF", "Pisahkan PDF"],
    ["Extract selected pages into separate PDFs.", "Pisahkan halaman pilihan menjadi file PDF terpisah."],
    ["Compress PDF", "Kompres PDF"],
    ["Reduce PDF file size while preserving readability.", "Kecilkan ukuran PDF sambil menjaga keterbacaan."],
    ["Rotate PDF", "Putar PDF"],
    ["Rotate pages by 90, 180 or 270 degrees.", "Putar halaman sebesar 90, 180, atau 270 derajat."],
    ["PDF to JPG", "PDF ke JPG"],
    ["Export PDF pages as image files.", "Ekspor halaman PDF sebagai file gambar."],
    ["JPG to PDF", "JPG ke PDF"],
    ["Arrange images and create a PDF document.", "Atur gambar dan buat dokumen PDF."],
    ["PDF to Word", "PDF ke Word"],
    ["Convert PDF content to an editable DOCX document.", "Konversi PDF menjadi dokumen DOCX yang dapat diedit."],
    ["Word to PDF", "Word ke PDF"],
    ["Convert a Word document to PDF.", "Konversi dokumen Word menjadi PDF."],
    ["PDF to Excel", "PDF ke Excel"],
    ["Extract PDF tables into an XLSX workbook.", "Ekstrak tabel PDF ke dalam workbook XLSX."],
    ["Add Watermark", "Tambahkan Watermark"],
    ["Place a text watermark on PDF pages.", "Tambahkan watermark teks pada halaman PDF."],
    ["Remove Pages", "Hapus Halaman"],
    ["Choose pages to remove from a PDF.", "Pilih halaman yang ingin dihapus dari PDF."],
    ["AI Summarizer", "Peringkas AI"],
    ["Turn long text into a concise summary and key points.", "Ringkas teks panjang menjadi rangkuman dan poin penting."],
    ["Text Rewriter", "Penulis Ulang Teks"],
    ["Rewrite text in a tone that fits your audience.", "Tulis ulang teks dengan nada yang sesuai untuk pembaca."],
    ["Translator", "Penerjemah"],
    ["Translate text across supported languages.", "Terjemahkan teks ke berbagai bahasa."],
    ["OCR", "OCR"],
    ["Extract readable text from an image or PDF.", "Ekstrak teks dari gambar atau PDF."],
    ["Image Upscaler", "Peningkat Resolusi Gambar"],
    ["Upscale images with an AI image provider.", "Tingkatkan resolusi gambar dengan penyedia AI."],
    ["AI Background Remover", "Penghapus Latar Belakang AI"],
    ["Remove image backgrounds with an AI provider.", "Hapus latar belakang gambar dengan penyedia AI."],
    ["PDF Chat", "Obrolan PDF"],
    ["Ask questions grounded in an uploaded PDF.", "Ajukan pertanyaan berdasarkan PDF yang diunggah."],
    ["Document Analyzer", "Penganalisis Dokumen"],
    ["Find topics, dates, entities and action items.", "Temukan topik, tanggal, entitas, dan tindak lanjut."],
    ["Text to Speech", "Teks ke Suara"],
    ["Turn written text into spoken audio.", "Ubah teks tertulis menjadi audio."],
    ["Password Generator", "Generator Kata Sandi"],
    ["Create a strong password with options you control.", "Buat kata sandi kuat dengan pengaturan sesuai kebutuhan."],
    ["We couldn’t find that tool", "Alat tidak ditemukan"],
    ["It may have moved, or the link may be incorrect.", "Alat mungkin sudah dipindahkan atau tautannya keliru."],
    ["Runs in your browser", "Berjalan di browser Anda"],
    ["Connected provider", "Penyedia terhubung"],
    ["Capture a screen", "Ambil tangkapan layar"],
    ["Choose a screen, app window, or browser tab in the system picker.", "Pilih layar, jendela aplikasi, atau tab browser pada pemilih sistem."],
    ["Browser capture", "Tangkapan layar browser"],
    ["Capturing…", "Mengambil gambar…"],
    ["Capture screen", "Ambil layar"],
    ["Download image", "Unduh gambar"],
    ["Image workspace", "Ruang kerja gambar"],
    ["Your file stays on this device while it’s being processed.", "File tetap berada di perangkat ini selama diproses."],
    ["Client-side", "Di perangkat Anda"],
    ["Remove", "Hapus"],
    ["Width", "Lebar"],
    ["Height", "Tinggi"],
    ["Aspect ratio locked", "Rasio aspek terkunci"],
    ["Unlock ratio", "Buka kunci rasio"],
    ["Quality", "Kualitas"],
    ["Format", "Format"],
    ["Output format", "Format keluaran"],
    ["Image ready to download", "Gambar siap diunduh"],
    ["Process image", "Proses gambar"],
    ["Paste a JWT token (eyJ...)", "Tempel token JWT (eyJ...)"],
    ["Enter a Unix timestamp or ISO date", "Masukkan timestamp Unix atau tanggal ISO"],
    ["Number of passwords to generate (optional)", "Jumlah kata sandi yang ingin dibuat (opsional)"],
    ["Try 404", "Coba 404"],
    ["Type or paste your input here...", "Ketik atau tempel masukan di sini..."],
    ["Modified text...", "Teks yang diubah..."],
    ["Excellent", "Sangat kuat"],
    ["Strong", "Kuat"],
    ["Good", "Baik"],
    ["Fair", "Cukup"],
    ["Password strength", "Kekuatan kata sandi"],
    ["Randomized with a secure browser generator.", "Dibuat secara acak dengan generator aman di browser."],
    ["Copied to clipboard.", "Disalin ke papan klip."],
    ["Your text is sent to the configured AI provider.", "Teks Anda dikirim ke penyedia AI yang dikonfigurasi."],
    ["Avoid entering confidential or personal data. Provider credentials stay on the server.", "Jangan masukkan data rahasia atau pribadi. Kredensial penyedia tetap di server."],
    ["Basic whitespace minification.", "Minifikasi spasi dasar."],
    ["Review the output before use. This simple formatter does not safely parse every JavaScript syntax or string literal.", "Tinjau hasil sebelum digunakan. Pemformat sederhana ini belum mendukung semua sintaks dan string JavaScript."],
    ["MD5 is not suitable for security.", "MD5 tidak cocok untuk kebutuhan keamanan."],
    ["Use SHA-256 or SHA-512 for security-sensitive applications.", "Gunakan SHA-256 atau SHA-512 untuk aplikasi yang membutuhkan keamanan."],
    ["Decoding is not verification.", "Dekode bukan verifikasi."],
    ["The signature is not checked. Never treat decoded claims as trusted until a server verifies the token.", "Tanda tangan tidak diperiksa. Jangan percaya klaim token sebelum server memverifikasinya."],
    ["KEEP EXPLORING", "JELAJAHI LEBIH LANJUT"],
    ["More", "Lainnya"],
    ["Browse category →", "Jelajahi kategori →"],
    ["Runs locally in your browser", "Berjalan lokal di browser Anda"],
    ["PROCESSING PROVIDER REQUIRED", "MEMERLUKAN PENYEDIA PEMROSESAN"],
    ["Connect an AI provider to get started.", "Hubungkan penyedia AI untuk memulai."],
    ["PDF processing engine required.", "Memerlukan mesin pemroses PDF."],
    ["QR encoding library required.", "Memerlukan pustaka pembuat QR."],
    ["Media processing engine required.", "Memerlukan mesin pemroses media."],
    ["This tool is designed to connect to a provider through a server side service. Add your provider key as an environment variable; keys are never exposed to the browser.", "Alat ini terhubung ke penyedia melalui layanan server. Tambahkan kunci penyedia sebagai variabel lingkungan; kunci tidak pernah ditampilkan di browser."],
    ["PDF editing and conversion needs a dedicated document engine. Connect a server side processor to enable file conversion while keeping file handling explicit.", "Pengeditan dan konversi PDF memerlukan mesin dokumen khusus. Hubungkan pemroses server untuk mengaktifkan konversi file."],
    ["Add a QR encoding package to enable downloadable PNG and SVG output.", "Tambahkan paket pembuat QR agar hasil dapat diunduh sebagai PNG dan SVG."],
    ["This format needs a processing engine that is not installed in this workspace. A provider adapter can be configured without exposing credentials.", "Format ini memerlukan mesin pemroses yang belum terpasang. Adapter penyedia dapat dikonfigurasi tanpa membuka kredensial."],
    ["Provider credentials stay server-side", "Kredensial penyedia tetap di server"],
    ["Privacy & architecture", "Privasi & arsitektur"],
    ["Simple by design", "Sederhana dan praktis"],
    ["No setup. Open the tool and get straight to work.", "Tanpa pengaturan. Buka alat dan langsung mulai bekerja."],
    ["Your privacy comes first", "Privasi Anda yang utama"],
    ["This tool runs locally in your browser.", "Alat ini berjalan lokal di browser Anda."],
    ["Your text is sent to the AI provider configured for this workspace.", "Teks Anda dikirim ke penyedia AI yang dikonfigurasi untuk ruang kerja ini."],
    ["File handling depends on the processing provider you connect.", "Pemrosesan file bergantung pada penyedia yang Anda hubungkan."],
    ["Built for everyone", "Dibuat untuk semua orang"],
    ["Clear controls and useful results, without the clutter.", "Kontrol yang jelas dan hasil berguna tanpa tampilan rumit."],
    ["Enter a valid JWT with a header and payload.", "Masukkan JWT yang memiliki header dan payload."],
    ["Enter a Unix timestamp or a valid date.", "Masukkan timestamp Unix atau tanggal yang valid."],
    ["Enter a 6-digit HEX color, for example #7c5cfc.", "Masukkan warna HEX 6 digit, misalnya #7c5cfc."],
    ["Choose a PNG, JPG, WebP, or AVIF image.", "Pilih gambar PNG, JPG, WebP, atau AVIF."],
    ["This image is larger than 20 megapixels and may be too large to process in this browser.", "Gambar ini lebih besar dari 20 megapiksel dan mungkin terlalu besar untuk diproses di browser."],
    ["Output must be 20 megapixels or smaller.", "Ukuran hasil maksimal 20 megapiksel."],
    ["This browser cannot export the selected format. Choose WebP or JPEG instead.", "Browser ini tidak dapat mengekspor format tersebut. Pilih WebP atau JPEG."],
    ["Could not process this image.", "Gambar tidak dapat diproses."],
    ["Screen capture was cancelled.", "Pengambilan layar dibatalkan."],
    ["Could not capture this screen.", "Layar tidak dapat diambil."],
    ["No matches found.", "Tidak ditemukan kecocokan."],
    ["No differences found.", "Tidak ditemukan perbedaan."],
    ["The AI provider could not complete this request.", "Penyedia AI tidak dapat menyelesaikan permintaan ini."],
    ["Strong", "Kuat"], ["Fair", "Cukup"], ["system", "Sistem"], ["Dark", "Gelap"], ["Light", "Terang"],
    ["Drop an image here, or", "Letakkan gambar di sini, atau"], ["browse files", "pilih file"], ["PNG, JPG, WebP or AVIF · Up to 25 MB", "PNG, JPG, WebP atau AVIF · Maksimal 25 MB"], ["Upload an image. Drop a file or paste from the clipboard.", "Unggah gambar. Letakkan file atau tempel dari papan klip."], ["Selected image preview", "Pratinjau gambar yang dipilih"],
    ["A BETTER WAY TO GET THINGS DONE", "Cara yang lebih mudah untuk menyelesaikan pekerjaan"],
    ["A collection of fast, simple, and useful online tools for everyone.", "Kumpulan alat online yang cepat, sederhana, dan berguna untuk semua orang."],
    ["OUR MISSION", "MISI KAMI"], ["Less friction.", "Lebih sedikit hambatan."], ["More making.", "Lebih banyak berkarya."],
    ["We believe everyday digital work should be easier. IMPHNEN brings practical tools together in one calm, focused workspace, so you can spend less time looking and more time doing.", "Kami percaya pekerjaan digital sehari-hari seharusnya lebih mudah. IMPHNEN menyatukan alat praktis dalam satu ruang kerja yang tenang agar Anda bisa mengurangi waktu mencari dan lebih banyak berkarya."],
    ["Your work stays", "Pekerjaan Anda tetap"], ["yours.", "milik Anda."],
    ["Tools marked as local run in your browser. Some advanced tools need a connected processing service. We label those requirements clearly, and provider credentials belong on the server.", "Alat bertanda lokal berjalan di browser Anda. Beberapa alat lanjutan memerlukan layanan pemrosesan. Persyaratan tersebut kami jelaskan, dan kredensial penyedia disimpan di server."],
    ["TECHNOLOGY", "TEKNOLOGI"], ["Built for speed", "Dibuat agar cepat"], ["and clarity.", "dan mudah digunakan."],
    ["Made with Next.js, React, and modern browser APIs. We prefer simple client-side processing when it can deliver a useful result without uploading your files.", "Dibuat dengan Next.js, React, dan API browser modern. Kami mengutamakan pemrosesan di perangkat jika hasil yang berguna dapat diperoleh tanpa mengunggah file."],
    ["SAY HELLO", "SAPA KAMI"], ["Have an idea", "Punya ide"], ["for a tool?", "untuk alat baru?"],
    ["We’re always looking for ways to make the toolkit more useful.", "Kami selalu mencari cara agar kumpulan alat ini semakin berguna."],
    ["Privacy, in plain language.", "Penjelasan privasi yang mudah dipahami."],
    ["IMPHNEN ONLINE TOOLS is designed to process compatible files directly in your browser.", "IMPHNEN ONLINE TOOLS dirancang untuk memproses file yang kompatibel langsung di browser Anda."],
    ["Browser processing", "Pemrosesan di browser"],
    ["Tools marked “Runs in your browser” process the input on your device. The image compressor, image resizer, image converter, JSON tools, encoders, generators, and other marked utilities do not upload that input to an IMPHNEN server.", "Alat bertanda “Berjalan di browser Anda” memproses masukan di perangkat Anda. Kompresor, pengubah ukuran dan konverter gambar, alat JSON, encoder, generator, serta alat lokal lainnya tidak mengunggah masukan ke server IMPHNEN."],
    ["Connected services", "Layanan terhubung"],
    ["AI tools send the text you submit to the AI provider configured by the site operator. Provider credentials are held server-side. Don’t submit confidential or personal information unless you are comfortable with that provider’s data practices.", "Alat AI mengirim teks yang Anda masukkan ke penyedia AI yang dikonfigurasi oleh pengelola situs. Kredensial penyedia disimpan di server. Jangan kirim informasi rahasia atau pribadi jika Anda belum memahami kebijakan data penyedia tersebut."],
    ["Some document and media tools show a provider setup notice until a processing service is connected. This version does not upload files for those tools.", "Beberapa alat dokumen dan media menampilkan pemberitahuan konfigurasi sampai layanan pemrosesan terhubung. Versi ini tidak mengunggah file untuk alat tersebut."],
    ["Preferences on this device", "Preferensi di perangkat ini"],
    ["Theme, language, favorite tools, and recently used tools are stored in your browser’s local storage. You can clear favorites and recent tools in Settings.", "Tema, bahasa, alat favorit, dan riwayat penggunaan disimpan di penyimpanan lokal browser. Anda dapat menghapus favorit dan riwayat melalui Pengaturan."],
    ["Contact", "Kontak"], ["For questions about this policy, contact the operator of the IMPHNEN ONLINE TOOLS deployment.", "Untuk pertanyaan tentang kebijakan ini, hubungi pengelola situs IMPHNEN ONLINE TOOLS."], ["Open privacy settings", "Buka pengaturan privasi"],
    ["USING THE TOOLKIT", "MENGGUNAKAN KUMPULAN ALAT"], ["Terms of use.", "Ketentuan penggunaan."],
    ["Use these tools responsibly and review the output before relying on it.", "Gunakan alat ini dengan bijak dan tinjau hasilnya sebelum mengandalkannya."],
    ["Provided as tools", "Penyediaan alat"],
    ["IMPHNEN ONLINE TOOLS provides utilities for convenience. Results can depend on browser support and connected service availability. Review generated, converted, or analyzed output for accuracy and suitability.", "IMPHNEN ONLINE TOOLS menyediakan alat untuk kemudahan Anda. Hasil dapat bergantung pada dukungan browser dan ketersediaan layanan terhubung. Periksa ketepatan dan kesesuaian hasil yang dibuat, dikonversi, atau dianalisis."],
    ["Your content", "Konten Anda"],
    ["You retain responsibility for content you enter or upload. Avoid submitting material you do not have permission to process. Tools that use an AI provider send submitted text to the provider configured for this deployment.", "Anda bertanggung jawab atas konten yang dimasukkan atau diunggah. Jangan kirim materi yang tidak berhak Anda proses. Alat yang menggunakan penyedia AI akan mengirim teks ke penyedia yang dikonfigurasi untuk situs ini."],
    ["Availability", "Ketersediaan"],
    ["Some tools require additional providers or processing engines. Their setup requirements are shown on the tool page. Features may change as the toolkit develops.", "Beberapa alat memerlukan penyedia tambahan atau mesin pemrosesan. Persyaratan konfigurasinya ditampilkan di halaman alat. Fitur dapat berubah seiring pengembangan."],
    ["Questions", "Pertanyaan"], ["For questions about this deployment, contact the IMPHNEN ONLINE TOOLS operator.", "Untuk pertanyaan mengenai situs ini, hubungi pengelola IMPHNEN ONLINE TOOLS."],
    ["Expand sidebar", "Buka sidebar"]
  ]);

export function translate(text: string, language: AppLanguage) {
  return language === "Indonesian" ? id[text] ?? text : text;
}

export function categoryName(category: "all" | "developer" | "media" | "pdf" | "ai", language: AppLanguage) {
  const names = { all: "All tools", developer: "Developer", media: "Media", pdf: "PDF", ai: "AI tools" };
  return translate(names[category], language);
}

export function useAppLanguage() {
  const [language, setLanguage] = useState<AppLanguage>("English");
  useEffect(() => {
    const update = () => {
      const saved = localStorage.getItem("imphnen-language");
      const next: AppLanguage = saved === "Indonesian" ? "Indonesian" : "English";
      setLanguage(next);
      document.documentElement.lang = next === "Indonesian" ? "id" : "en";
    };
    update();
    window.addEventListener("imphnen-language-change", update);
    window.addEventListener("storage", update);
    return () => {
      window.removeEventListener("imphnen-language-change", update);
      window.removeEventListener("storage", update);
    };
  }, []);
  return language;
}
