export type Category = "developer" | "media" | "pdf" | "ai";
export type Tool = { slug: string; name: string; category: Category; description: string; icon: string; popular?: boolean; local?: boolean; tags?: string[] };

const entries: [Category, string, string, string, boolean?, boolean?][] = [
  ["developer","JSON Formatter","Format, validate and minify JSON with a clean tree view.","{ }",true,true], ["developer","JWT Decoder","Inspect token headers and payloads. Signature is never verified.","◈",true,true], ["developer","UUID Generator","Generate secure UUID v4 identifiers in seconds.","⠿",true,true], ["developer","Base64 Converter","Encode text or decode Base64 right in your browser.","⇄",true,true], ["developer","URL Encoder / Decoder","Encode and decode URL components safely.","↗",false,true], ["developer","Hash Generator","Create MD5, SHA-1, SHA-256 and SHA-512 digests.","#",false,true], ["developer","Regex Tester","Test patterns, flags and capture groups interactively.",".*",true,true], ["developer","Diff Checker","Compare two texts and spot additions and removals.","±",false,true], ["developer","Timestamp Converter","Convert Unix timestamps and dates instantly.","◷",false,true], ["developer","Cron Generator","Build a cron expression from a readable schedule.","◷",false,true], ["developer","SQL Formatter","Make SQL queries easier to read and review.","▤",false,true], ["developer","HTML Minifier","Remove unnecessary whitespace from HTML.","‹›",false,true], ["developer","CSS Minifier","Compress CSS source for smaller files.","#",false,true], ["developer","JavaScript Minifier","Compact compatible JavaScript source code.","JS",false,true], ["developer","Markdown Preview","Write Markdown and preview the rendered result.","M↓",false,true], ["developer","URL Parser","Inspect URL parts and query parameters.","⌁",false,true], ["developer","HTTP Status Checker","Look up standard HTTP response status codes.","↔",false,true],
  ["media","Image Compressor","Reduce image size and compare the result before download.","▧",true,true], ["media","Image Resizer","Resize images with an optional locked aspect ratio.","⤢",false,true], ["media","Image Converter","Convert images between PNG, JPEG and WebP.","◫",true,true], ["media","Color Picker","Explore a color and copy HEX, RGB or HSL values.","◉",false,true], ["media","QR Generator","Create a QR code for links, text, WiFi and contacts.","▦",true,false], ["media","Background Remover","Remove image backgrounds with an AI provider.","✦",false], ["media","GIF Maker","Turn image frames into an animated GIF.","GIF",false], ["media","Video Compressor","Compress video with control over output quality.","▶",false], ["media","Audio Converter","Convert common audio formats.","♫",false], ["media","Video to GIF","Create a GIF from a video clip.","▣",false], ["media","Screenshot to Image","Capture a selected screen and save it as an image.","▧",false,true],
  ["pdf","Merge PDF","Combine PDF documents into one file.","▤",true], ["pdf","Split PDF","Extract selected pages into separate PDFs.","⊞",false], ["pdf","Compress PDF","Reduce PDF file size while preserving readability.","⇣",false], ["pdf","Rotate PDF","Rotate pages by 90, 180 or 270 degrees.","⟳",false], ["pdf","PDF to JPG","Export PDF pages as image files.","▧",false], ["pdf","JPG to PDF","Arrange images and create a PDF document.","▤",false], ["pdf","PDF to Word","Convert PDF content to an editable DOCX document.","W",false], ["pdf","Word to PDF","Convert a Word document to PDF.","W",false], ["pdf","PDF to Excel","Extract PDF tables into an XLSX workbook.","▦",false], ["pdf","Add Watermark","Place a text watermark on PDF pages.","◈",false], ["pdf","Remove Pages","Choose pages to remove from a PDF.","⊟",false],
  ["ai","AI Summarizer","Turn long text into a concise summary and key points.","✦",true], ["ai","Text Rewriter","Rewrite text in a tone that fits your audience.","↻",false], ["ai","Translator","Translate text across supported languages.","文",false], ["ai","OCR","Extract readable text from an image or PDF.","⌕",false], ["ai","Image Upscaler","Upscale images with an AI image provider.","↗",false], ["ai","AI Background Remover","Remove image backgrounds with an AI provider.","✦",false], ["ai","PDF Chat","Ask questions grounded in an uploaded PDF.","◌",false], ["ai","Document Analyzer","Find topics, dates, entities and action items.","⌕",false], ["ai","Text to Speech","Turn written text into spoken audio.","♫",false],
  ["developer","Password Generator","Create a strong password with options you control.","⚿",true,true], ["developer","Color Picker","Convert and copy precise color values.","◉",false,true], ["developer","Base64 Encoder / Decoder","Convert between plain text and Base64.","⇄",false,true], ["developer","URL Parser","Break a URL into its component parts.","⌁",false,true]
];
const slugify = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const seen = new Set<string>();
export const tools: Tool[] = entries.map(([category,name,description,icon,popular,local]) => ({ slug: slugify(name), category, name, description, icon, popular, local, tags: [name, category] })).filter(t => !seen.has(t.slug) && !!seen.add(t.slug));
export const categories: { id: Category | "all"; label: string; icon: string; count: number }[] = [
  {id:"all",label:"All tools",icon:"⌘",count:tools.length},{id:"developer",label:"Developer",icon:"⌘",count:tools.filter(t=>t.category==="developer").length},{id:"media",label:"Media",icon:"▧",count:tools.filter(t=>t.category==="media").length},{id:"pdf",label:"PDF",icon:"▤",count:tools.filter(t=>t.category==="pdf").length},{id:"ai",label:"AI tools",icon:"✦",count:tools.filter(t=>t.category==="ai").length}
];
export const categoryLabels: Record<Category,string> = { developer:"Developer tools", media:"Media tools", pdf:"PDF tools", ai:"AI tools" };
export const getTool = (slug: string) => tools.find(t => t.slug === slug);
